info:
    component: 'Ticketservice'

spring:
    application:
        name: tickets
#    zipkin:
#        baseUrl: http://10.1.102.175:9411
#    sleuth:
#        enabled: true
#        sampler:
#            percentage: 1.0

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG



---
# For deployment without Docker containers
spring:
  profiles: default

server:
    port: 8080

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: ${vcap.services.eureka-service.credentials.uri:http://localhost:8761}/eureka/

---
# For deployment in Docker containers
spring:
  profiles: docker

server:
    port: 80

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/